[bundle]
name = "texlive2023"
expected_hash = "442a4d6e136965fb5ad5110efc8074584eb7e61f98340abec220d7d0fad2d887"

search_order = ["/", { input = "include" }, { input = "texlive" }]

# Note the triple-quoted multiline strings:
# this is the best way to get raw strings in TOML.
ignore = [
    # Files and extensions we usually want to ignore.
    '''.*/00readme\.txt''',
    '''.*/LICENSE\.md''',
    '''.*/Makefile''',
    '''.*/README''',
    '''.*/README.md''',
    '''.*/readme\.txt''',
    '''.*/ls-R''',
    '''.*\.fmt''',
    '''.*\.log''',
    '''.*\.lua''',
    '''.*\.mf''',
    '''.*\.pl''',
    '''.*\.ps''',
]


[inputs."include"]
source.type = "directory"
source.path = "include"

# texlive-20230313-texmf
[inputs."texlive"]
source.type = "tarball"
source.hash = "ac1683d4abeb7fd534851ad7ff0ec891da7da4729603506efd0245259dcdcc67"
patch_dir = "patches/texlive"

ignore = [
    # I don't think tectonic has xindy support, ignore for now
    '''xindy/.*''',

    # We may need this, but exclude for now.
    '''tex4ht/.*''',

    # These require pLaTeX2e, tectonic uses XeTeX
    '''tex/uplatex/.*''',
    '''tex/uptex/.*''',

    # Other odd tex formats & unnecessary files
    '''tex/cslatex/.*''',
    '''tex/csplain/.*''',
    '''tex/ptex/.*''',
    '''tex/platex/.*''',
    '''tex/lollipop/.*''',
    '''tex/context/.*''',
    '''context/.*''',
    '''texdoc/.*''',
    '''texdoctk/.*''',
    '''texconfig/.*''',
    '''scripts/.*''',
    '''dvips/.*''',
    '''asymptote/.*''',
    '''makeindex/.*''',
    '''luatex-cache/.*''',
    '''hb2gf/.*''',
    '''chktex/.*''',
    '''source/.*''',
    '''doc/.*''',
    '''tex/luatex/.*''',
    '''tex/lualatex/.*''',
    '''tex/lambda/.*''',
    '''omega/.*''',
]

search_order = [
    "tex/{xelatex,latex,xetex,plain,generic}//",
    "bibtex/{bib,bst,csf}//",
    "web2c//",
    "fonts//",
    "biber//",
    "mft//",
    "dvips//",
    "makeindex//",
    "{web,cweb}//",
    "ttf2pk//",
    "dvipdfmx/",
]
