name = "texlive2023"

texlive_name = "texlive-20230313-texmf"
texlive_hash = "ac1683d4abeb7fd534851ad7ff0ec891da7da4729603506efd0245259dcdcc67"
result_hash = "442a4d6e136965fb5ad5110efc8074584eb7e61f98340abec220d7d0fad2d887"


search_order = [
    "/",
    "/include//",
    "/texlive/tex/{xelatex,latex,xetex,plain,generic}//",
    "/texlive/bibtex/{bib,bst,csf}//",
    "/texlive/web2c//",
    "/texlive/fonts//",
    "/texlive/biber//",
    "/texlive/mft//",
    "/texlive/dvips//",
    "/texlive/makeindex//",
    "/texlive/{web,cweb}//",
    "/texlive/ttf2pk//",
    "/texlive/dvipdfmx/",
]

# Note the triple-quoted multiline strings:
# this is the best way to get raw strings in TOML.
ignore = [
    # Files and extensions we usually want to ignore.
    '''.*/00readme\.txt''',
    '''.*/LICENSE\.md''',
    '''.*/Makefile''',
    '''.*/README''',
    '''.*/README.md''',
    '''.*/readme\.txt''',
    '''.*/ls-R''',
    '''.*\.fmt''',
    '''.*\.log''',
    '''.*\.lua''',
    '''.*\.mf''',
    '''.*\.pl''',
    '''.*\.ps''',

    # I don't think tectonic has xindy support, ignore for now
    '''/texlive/xindy/.*''',

    # We may need this, but exclude for now.
    '''/texlive/tex4ht/.*''',

    # These require pLaTeX2e, tectonic uses XeTeX
    '''/texlive/tex/uplatex/.*''',
    '''/texlive/tex/uptex/.*''',

    # Other odd tex formats & unnecessary files
    '''/texlive/tex/cslatex/.*''',
    '''/texlive/tex/csplain/.*''',
    '''/texlive/tex/ptex/.*''',
    '''/texlive/tex/platex/.*''',
    '''/texlive/tex/lollipop/.*''',
    '''/texlive/tex/context/.*''',
    '''/texlive/context/.*''',
    '''/texlive/texdoc/.*''',
    '''/texlive/texdoctk/.*''',
    '''/texlive/texconfig/.*''',
    '''/texlive/scripts/.*''',
    '''/texlive/dvips/.*''',
    '''/texlive/asymptote/.*''',
    '''/texlive/makeindex/.*''',
    '''/texlive/luatex-cache/.*''',
    '''/texlive/hb2gf/.*''',
    '''/texlive/chktex/.*''',
    '''/texlive/source/.*''',
    '''/texlive/doc/.*''',
    '''/texlive/tex/luatex/.*''',
    '''/texlive/tex/lualatex/.*''',
    '''/texlive/tex/lambda/.*''',
    '''/texlive/omega/.*''',
]
